donenv/urls.py
from django.contrib import admin
from django.urls import path
from app import views
from django.conf import settings 
from django.conf.urls.static import static 
from django.contrib.auth import views as auth_views
from app.forms import MyPasswordResetForm, MySetPasswordForm


urlpatterns = [
    path("admin/", admin.site.urls),
    path("", views.index, name="index"),
    path("gallery", views.gallery, name="gallery"),

    path('password-reset/', auth_views.PasswordResetView.as_view(template_name='password-reset.html',form_class=MyPasswordResetForm),name='password_reset'),
    path('password-reset-done/', auth_views.PasswordResetDoneView.as_view(template_name='password-reset-done.html'), name='password_reset_done'),
    path('password-reset-confirm/<uidb64>/<token>/', auth_views.PasswordResetConfirmView.as_view(template_name='password-reset-confirm.html',form_class=MySetPasswordForm),name='password_reset_confirm'),
    path('password-reset-complete/', auth_views.PasswordResetCompleteView.as_view(template_name='password-reset-complete.html'),name='password_reset_complete'),

    #Donor URLS
    path("donor/login-donor", views.login_donor.as_view(), name="login_donor"),
    path("donor/signup-donor/", views.signup_donor.as_view(), name="signup_donor"),
    path("donor/index-donor", views.index_donor, name="index_donor"),
    path("donor/donate-now/", views.donate_now.as_view(), name="donate_now"),
    # path("donor/donation-history/", views.donation_history, name="donation_history"),
    path("donor/profile-donor/", views.profile_donor.as_view(), name="profile_donor"),
    path("donor/donation-list/all", views.donor_all, name="donor_donation_all"),
    path("donor/donation-list/accepted", views.donor_accepted_donation, name="donor_accepted_donation"),
    path("donor/donation-list/rejected", views.donor_rejected_donation, name="donor_rejected_donation"),
    path("donor/donation-list/pending", views.donor_pending_donation, name="donor_pending_donation"),
    path("donor/donation-list/delivered", views.donor_delivered_donation, name="donor_delivered_donation"),
    path("donor/changepwd-donor/", views.changepwd_donor.as_view(), name="changepwd_donor"),
    path(
        "donor/donationdetail-donor/<int:pid>",
        views.donationdetail_donor,
        name="donationdetail_donor",
    ),



    #Volunteer URLS
    path("volunteer/login-volunteer", views.login_volunteer.as_view(), name="login_volunteer"),
    path("volunteer/signup-volunteer/", views.signup_volunteer.as_view(), name="signup_volunteer"),
    path("volunteer/index-volunteer/", views.index_volunteer, name="index_volunteer"),
    path("volunteer/changepwd-volunteer/", views.changepwd_volunteer.as_view(), name="changepwd_volunteer"),
    path("volunteer/profile-volunteer/", views.profile_volunteer.as_view(), name="profile_volunteer"),
    path("volunteer/donation-list/new-collection-request", views.volunteer_new_collection_request, name="volunteer_new_collection_request"),
    path("volunteer/donation-list/donation-received", views.volunteer_donation_received, name="volunteer_donation_received"),
    path("volunteer/donation-list/donation-not-received", views.volunteer_donation_not_received, name="volunteer_donation_not_received"),
    path("volunteer/donation-list/donation-delivered", views.volunteer_donation_delivered, name="volunteer_donation_delivered"),

    
    path(
        "volunteer/donationcollection-detail/<int:pid>",
        views.donationcollection_detail.as_view(),
        name="donationcollection_detail",
    ),
    path(
        "volunteer/donation-list/donationdelivered-volunteer/",
        views.donationdelivered_volunteer,
        name="donationdelivered_volunteer",
    ),
     path(
        "volunteer/donation-list/donationnotrec-volunteer/",
        views.donationnotrec_volunteer,
        name="donationnotrec_volunteer",
    ),
     path(
        "volunteer/donationrec-detail/<int:pid>",
        views.donationrec_detail.as_view(),
        name="donationrec_detail",
    ),
    path(
        "volunteer/donation-list/donationrec-volunteer/",
        views.donationrec_volunteer,
        name="donationrec_volunteer",
    ),
    
    # Admin URLS
    path("admin-panel/login-admin", views.login_admin.as_view(), name="login_admin"),
    path("admin-panel/index-admin/", views.index_admin, name="index_admin"),
    path("admin-panel/accepted-donation/", views.accepted_donation, name="accepted_donation"),
    path("admin-panel/add-area/", views.add_area.as_view(), name="add_area"),
    path("admin-panel/accepted-volunteer/", views.accepted_volunteer, name="accepted_volunteer"),
    path("admin-panel/all-donations/", views.all_donations, name="all_donations"),
    path("admin-panel/all-volunteer/", views.all_volunteer, name="all_volunteer"),
    path("admin-panel/changepwd-admin/", views.changepwd_admin.as_view(), name="changepwd_admin"),
    path("admin-panel/donationrec-admin/", views.donationrec_admin, name="donationrec_admin"),
    path("admin-panel/edit-area/<int:pid>", views.edit_area.as_view(), name="edit_area"),
    path("admin-panel/manage-area/", views.manage_area, name="manage_area"),
    path("admin-panel/manage-donor/", views.manage_donor, name="manage_donor"),
    path("admin-panel/new-volunteer/", views.new_volunteer, name="new_volunteer"),
    path("admin-panel/pending-donation/", views.pending_donation, name="pending_donation"),
    path("admin-panel/rejected-donation/", views.rejected_donation, name="rejected_donation"),
    path("admin-panel/rejected-volunteer/", views.rejected_volunteer, name="rejected_volunteer"),
    path("admin-panel/view-donordetail/<int:pid>", views.view_donordetail, name="view_donordetail"),
    

    path(
        "admin-panel/donationnotrec-admin/", views.donationnotrec_admin, name="donationnotrec_admin"
    ),
    path(
        "admin-panel/accepted-donationdetail/<int:pid>",
        views.accepted_donationdetail.as_view(),
        name="accepted_donationdetail",
    ),
    path(
        "admin-panel/donationdelivered-admin/",
        views.donationdelivered_admin,
        name="donationdelivered_admin",
    ),
    path(
        "admin-panel/view-donationdetail/<int:pid>",
        views.view_donationdetail.as_view(),
        name="view_donationdetail",
    ),
    path(
        "admin-panel/view-volunteerdetail/<int:pid>",
        views.view_volunteerdetail.as_view(),
        name="view_volunteerdetail",
    ),
    path(
        "admin-panel/volunteerallocated-donation/",
        views.volunteerallocated_donation,
        name="volunteerallocated_donation",
    ),
    
    #Common URL
    path("logout/", views.logoutView, name="logout"),
    path('delete_donation/<int:pid>', views.delete_donation, name='delete_donation'),
    path('delete_volunteer/<int:pid>',views.delete_volunteer,name='delete_volunteer'),
    path('delete_area/<int:pid>',views.delete_area, name='delete_area'),
    path('delete-donor/<int:pid>',views.delete_donor, name='delete_donor'),
    path("about", views.about, name="about"),
    path("contact", views.contact, name="contact"),
 ]

urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

app/models.py
from django.db import models
from django.contrib.auth.models import User



# Create your models here.
class Donor(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    contact = models.CharField(max_length=15,null=True)
    address = models.CharField(max_length=300,null=True)
    userpic = models.ImageField(upload_to='donor',null=True, blank=True)
    regdate = models.DateTimeField(auto_now_add=True)
    def __str__(self):
        return self.user.username
    
class Volunteer(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    contact = models.CharField(max_length=15,null=True)
    address = models.CharField(max_length=300,null=True)
    userpic = models.ImageField(upload_to='volunteer',null=True, blank=True)
    idpic = models.ImageField(upload_to='volunteer',null=True, blank=True)
    aboutme = models.CharField(max_length=300,null=True)
    status = models.CharField(max_length=20,null=True)
    regdate = models.DateTimeField(auto_now_add=True)
    adminremark = models.CharField(max_length=300, null=True)
    updationdate = models.DateField(null=True)

    def __str__(self):
        return self.user.username
    
class DonationArea(models.Model):
    areaname = models.CharField(max_length=100)
    creationdate = models.DateTimeField(auto_now_add=True)
    def __str__(self):
        return self.areaname
    
DONATION_CHOICES=(
         ('Food Donation','Food Donation'),
        ('Cloth Donation','Cloth Donation'),
        ('Blood Donation','Blood Donation'),
        ('Books Donation','Books Donation'),
        ('Furniture Donation','Furniture Donation'),
        ('Vessel Donation','Vessel Donation'),
        ('Organ Donation','Organ Donation'),
        ('Art Donation','Art Donation'),
        ('Cash Donation','Cash Donation'),
        ('Medical Donation','Medical Donation'),
        ('Plant Donation','Plant Donation'),
        ('Other Donation', 'Other Donation'),

    )
    
class Donation(models.Model):
    donor = models.ForeignKey(Donor, on_delete=models.CASCADE)
    donationname = models.CharField(choices=DONATION_CHOICES,max_length=100,null=True)
    donationpic = models.ImageField(upload_to='donation',null=True, blank=True)
    collectionloc = models.CharField(max_length=300,null=True)
    description = models.CharField(max_length=300,null=True)
    status = models.CharField(max_length=30,null=True)
    donationdate = models.DateField(null=True)
    adminremark = models.CharField(max_length=200, null=True)
    volunteer = models.ForeignKey(Volunteer, on_delete=models.CASCADE,null=True)
    donationarea = models.ForeignKey(DonationArea, on_delete=models.CASCADE,null=True)
    volunteermark = models.CharField(max_length=200, null=True)
    updationdate = models.DateField(null=True)
    def __str__(self):
        return str(self.id)

class Gallery(models.Model):
    donation = models.ForeignKey(Donation, on_delete=models.CASCADE)
    deliverypic = models.ImageField(upload_to='gallery',null=True, blank=True)
    creationdate = models.DateTimeField(auto_now_add=True)
    def __str__(self):
        return str(self.id)  
    
class Profile(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE) # Delete profile when user is deleted
    image = models.ImageField(default='default.jpg', upload_to='profile_pics')

    def __str__(self):
        return f'{self.user.username} Profile' #show how we want it to be displayed
        



        

app/templates/volunteer/base-db-volunteer.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
    <head>
        <meta charset="utf-8">
        <title>Volunteer Portal</title>
        <meta content="width=device-width, initial-scale=1.0" name="viewport">
        <meta content="" name="keywords">
        <meta content="" name="description">
    
        <!-- Favicon -->
        <link href="{% static 'img/favicon.ico' %}" rel="icon">
    
        <!-- Google Web Fonts -->
        <link rel="preconnect" href="https://fonts.googleapis.com">
        <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
        <link href="https://fonts.googleapis.com/css2?family=Inter:wght@400;500;600&family=Saira:wght@500;600;700&display=swap" rel="stylesheet"> 
        
        <!-- Icon Font Stylesheet -->
        <link href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.10.0/css/all.min.css" rel="stylesheet">
        <link href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.4.1/font/bootstrap-icons.css" rel="stylesheet">
    
        <!-- Libraries Stylesheet -->
        <link href="{% static 'lib/owlcarousel/assets/owl.carousel.min.css' %}" rel="stylesheet">
        <link href="{% static 'lib/tempusdominus/css/tempusdominus-bootstrap-4.min.css' %}" rel="stylesheet" />
    
        <!-- Customized Bootstrap Stylesheet -->
        <link rel="stylesheet" href="{% static 'css/bootstrap.min.css' %}" >
    
        <!-- Template Stylesheet -->
        <link rel="stylesheet" href="{% static 'css/style-admin.css' %}">
    </head>

<body >
   
     <!-- Sidebar Start -->
     <div class="sidebar pb-3 bg-dark">
            
        <nav class="navbar  navbar-light">
            <a href="{% url 'index_volunteer' %}" class="navbar-brand mx-4 mb-3">
                <h1 class="fw-bold text-primary m-0">One<span class="text-white">Mission</span></h1>
            </a>
            <div class="d-flex align-items-center ms-4 mb-4">
                <div class="position-relative rounded-circle border border-5 border-white">
                    {% if request.user.volunteer_set.all.first.userpic %}
                        <img class="rounded-circle" src="{{ request.user.volunteer_set.all.first.userpic.url }}" alt="Default Image" style="width: 60px; height: 60px;">
                    {% endif %}
                </div>
                <div class="ms-3 text-white">
                    
                    <h6 class="mb-0 text-white">{{request.user.first_name}} {{request.user.last_name}}</h6>
                    <span>Volunteer</span>
                </div>
            </div>
            <div class="navbar-nav w-100 text-white">
                <a href="{% url 'index_volunteer' %}" class="nav-item nav-link {% if request.path == '/volunteer/index-volunteer/' %}active{% endif %}"><i class="fa fa-tachometer-alt me-2"></i>Dashboard</a>
                <a href="{% url 'volunteer_new_collection_request' %}" class="nav-item nav-link {% if request.path == '/volunteer/donation-list/new-collection-request' %}active{% endif %}"><i class="fa fa-users me-2"></i>Donation Collection<br>Request</a>
                <div class="nav-item dropdown">
                    <a href="#" class="nav-link dropdown-toggle {% if request.path in collection_history_active_paths %}active{% endif %}" data-bs-toggle="dropdown"><i class="fa fa-info-circle me-2"></i>Collection History</a>
                    <div class="dropdown-menu bg-transparent border-0">
                        <a href="{% url 'volunteer_donation_received' %}" class="dropdown-item {% if request.path == '/volunteer/donation-list/donationrec-volunteer/' %}active{% endif %}" style="color:white;">Donation Received</a>
                        <a href="{% url 'volunteer_donation_not_received' %}" class="dropdown-item {% if request.path == '/volunteer/donation-list/donationnotrec-volunteer/' %}active{% endif %}" style="color:white;">Donation Not Received</a>
                        <a href="{% url 'volunteer_donation_delivered' %}" class="dropdown-item {% if request.path == '/volunteer/donation-list/donationdelivered-volunteer/' %}active{% endif %}" style="color: white; .dropdown-item:hover {background-color:white; color: black;">Donation Delivered</a>
                    </div>
                </div>
                <a href="{% url 'profile_volunteer' %}" class="nav-item nav-link {% if request.path == '/volunteer/profile-volunteer/' %}active{% endif %}"><i class="fa fa-user me-2"></i>Profile</a>
                <a href="{% url 'changepwd_volunteer' %}" class="nav-item nav-link {% if request.path == '/volunteer/changepwd-volunteer/' %}active{% endif %}"><i class="fa fa-key me-2"></i>Change Password</a>
                <a href="{% url 'logout' %}" class="nav-item nav-link {% if request.path == '/Logout' %}active{% endif %}"><i class="fa fa-sign-out me-2"></i>Logout</a>
                
            </div>
        </nav>
    </div>
    <!-- Sidebar End -->
    <div class="content">
        {% block main %}
        {% endblock main %}
    </div>   
    {% include 'base-db-footer.html' %}         

app/templates/volunteer/changepwd-volunteer.html
{% extends 'volunteer/base-db-volunteer.html' %}
{% load static %}
{% block main %}
<div class="container mt-5 vh-100 table-responsive">
    <h3>Change Password</h3>
    <hr>
    <div class="row">

        <form action="" method="post" novalidate>
            {% csrf_token %}
            {% for fm in form %}
                <div class="form-group col-sm-12 p-3">
                  {{fm}} <small class="text-danger">{{fm.errors|striptags}}</small>
                </div>
            {% endfor %}

            <div class="d-grid gap-2">
                <input type="submit" class="mt-4 px-3 btn btn-primary">
            </div>
        </form>
        
  
</div>
{% if form.non_field_errors %}
    {% for error in form.non_field_errors %}
        <p class="alert alert-danger my-3">{{ error }}</p>
    {% endfor %}
{% endif %}

{% if messages %}
    {% for message in messages %}
        <h3 {% if message.tags %} class="text-center alert alert-{{ message.tags }} my-5" {% endif %}>{{ message }}</h3>
    {% endfor %}
{% endif %}
  </div>
{% endblock main %}

app/templates/volunteer/collection-req.html
{% extends 'volunteer/base-db-volunteer.html' %}
{% load static %}
{% block main %}
<div class="container mt-5 table-responsive">
    <h3>New Donation Collection Request</h3>
    <hr>
    <table id="mytable" class="table data">
        <thead class="table-dark">
            <tr class="text-center">
                <th scope="col">#</th>
                <th scope="col">Donation Name</th>
                <th scope="col">Donation Date</th>
                <th scope="col">Action</th>
              </tr>
        </thead>
        <tbody>
          {% for i in donation %}
            <tr class="text-center">
                <td>{{forloop.counter}}</td>
                <td>{{i.donationname}}</td>
                <td>{{i.donationdate}}</td>
                <td><a href="{% url 'donationcollection_detail' i.id %}" class="text-primary">View Details</a></td>
              </tr>
        {% endfor %}
        </tbody>
    </table>
  </div>
{% endblock main %}

app/templates/volunteer/donation-list.html
{% extends 'volunteer/base-db-volunteer.html' %}
{% load static %}
{% block main %}
<div class="container mt-5 table-responsive">
    <h3>{{title}}</h3>
    <hr>
    <table id="mytable" class="table data">
        <thead class="table-dark">
            <tr class="text-center">
                <th scope="col">#</th>
                <th scope="col">Donation Name</th>
                <th scope="col">Donation Date</th>
                <th scope="col">Action</th>
              </tr>
        </thead>
        <tbody>
          {% for i in donation %}
            <tr class="text-center">
                <td>{{forloop.counter}}</td>
                <td>{{i.donationname}}</td>
                <td>{{i.donationdate}}</td>
                <td>
                  {% if i.status == "Volunteer Allocated" %}
                      <a href="{% url 'donationcollection_detail' i.id %}" class="text-primary"><u>View Details</u></a>
                  {% else %}
                      <a href="{% url 'donationrec_detail' i.id %}" class="text-primary"><u>View Details</u></a>
                  {% endif %}
              </td>
              </tr>
        {% endfor %}
        </tbody>
    </table>
  </div>
{% endblock main %}

app/templates/volunteer/donationcollection-detail.html
{% extends 'volunteer/base-db-volunteer.html' %}
{% load static %}
{% block main %}
<div class="container table-responsive primary-light">
  <h3 class="py-3 mt-1 text-center shadow">View Accepted Donation Detail</h3>
  
  <!-- Donor Details -->
  <div class="shadow p-2">
    <h4 class="text-center">Donor Details</h4>
    <div class="row p-2 justify-content-center">
      <div class="col-md-3">
          <div class="mb-3">
            {% if donation.donor.userpic %}
                <img class="rounded" src="{{ donation.donor.userpic.url }}" alt="Default Image" width="100%">
            {% endif %}
          </div>
      </div>
    
      <div class="col-md-4">
        <div class="form-group mt-1">
          <lable>Name</lable>
          <input class="form-control" readonly value="{{ donation.donor.user.first_name }} {{ donation.donor.user.last_name }}">
        </div>
        <div class="form-group mt-1">
          <lable>Contact</lable>
          <input class="form-control" readonly value="{{ donation.donor.contact }}">
        </div>
        <div class="form-group mt-1">
          <lable>Email</lable>
          <input class="form-control" readonly value="{{ donation.donor.user.email }}">
        </div>
      </div>
    </div>
  </div>

  <!-- Donation Details -->
  <div class="shadow mt-3 p-2 mb-5">
    <h4 class="text-center">Donation Details</h4>
    <div class="row p-2 justify-content-center">
      <div class="col-md-6">
        <div class="mb-3">
          <img src="{{donation.donationpic.url}}"  width="100%" />
        </div>
      </div>

      
      <div class="col-md-6">
        <div class="form-group mt-1">
          <lable>Name</lable>
          <input class="form-control" readonly value="{{ donation.donationname }}">
        </div>
        <div class="form-group mt-1">
          <lable>Collection Location</lable>
          <input class="form-control" readonly value="{{ donation.collectionloc }}">
        </div>
        <div class="form-group mt-1">
          <lable>Donation Date</lable>
          <input class="form-control" readonly value="{{ donation.donationdate }}">
        </div>
        <div class="form-group mt-2">
          <lable>Status</lable>
          <input class="text-center 
          {% if donation.status == 'reject' %}bg-danger
          {% elif donation.status == 'pending' %}bg-warning text-dark
          {% elif donation.status == 'Donation Delivered Successfully' %}bg-success
          {% else %}bg-info text-dark
          {% endif %} 
          font-weight-bold text-light rounded-pill p-0 img-wa" 
          readonly value="{{ donation.status }}">        </div>
        <div class="form-group mt-1">
          <lable>Updation Date</lable>
          <input class="form-control" readonly value="{{ donation.updationdate }}">
        </div>
      </div>
    </div>
    
    <div class="form-group mt-1">
      <lable>Admin Remark</lable>
      <input class="form-control" readonly value="{{ donation.adminremark }}" style="height:100px">
    </div>
    <div class="form-group mt-1">
      <lable>Donation Area</lable>
      <input class="form-control" readonly value="{{ donation.donationarea.areaname }}">
    </div>
    <div class="form-group mt-1">
      <lable>Volunteer</lable>
      <input class="form-control" readonly value="{{ donation.volunteer.user.first_name }} {{ donation.volunteer.user.last_name }}">
    </div>
    {% if donation.status == 'Volunteer Allocated'%}
      <form method="post">
        {% csrf_token %}

        <div class="align-middle mt-1">
          <lable >Donation Received ?</lable>
          <div colspan="3">
            <h5 class="text-secondary">
              <input type="radio" name="status" value="Donation Received" required> Donation Received
              <input type="radio" name="status" value="Donation NotReceived" required> Donation Not Received
            </h5>
          </div>
        </div> 
        <div class="form-group mt-1">
          <lable>Volunteer Remark</lable>
          <textarea class="form-control" name ="volunteerremark" id="exampleFormControlTextarea1" rows="3"></textarea>
        </div>

        <div class="align-middle text-center mt-3">
          <td></td>
          <div colspan="3">
              <input type="submit" class="btn btn-primary px-5" />
          </div>
        </div>
      {% else %}
      <div class="form-group mt-1">
        <lable>Volunteer Remark</lable>
        <input class="form-control" readonly value="{{ donation.volunteermark|default_if_none:"" }}">
      </div>
      {% endif %}
  </div>
  {% endblock main %}




  

app/templates/volunteer/donationrec-detail.html
{% extends 'volunteer/base-db-volunteer.html' %}
{% load static %}
{% block main %}
<div class="container table-responsive primary-light">
  <h3 class="py-3 mt-1 text-center shadow ">View Accepted Donation Detail</h3>

  <!-- Donor Details -->
  <div class="shadow p-2">
    <h4 class="text-center">Donor Details</h4>
    <div class="row p-2 justify-content-center">
      <div class="col-md-3">
          <div class="mb-3">
            {% if  donation.donor.userpic %}
               <img  src="{{ donation.donor.userpic.url }}" alt="Default Image" class="rounded" width="100%">
           {% endif %}
          </div>
      </div>
    
      <div class="col-md-4">
        <div class="form-group mt-1">
          <lable>Name</lable>
          <input class="form-control" readonly value="{{ donation.donor.user.first_name }} {{ donation.donor.user.last_name }}">
        </div>
        <div class="form-group mt-1">
          <lable>Contact</lable>
          <input class="form-control" readonly value="{{ donation.donor.contact }}">
        </div>
        <div class="form-group mt-1">
          <lable>Email</lable>
          <input class="form-control" readonly value="{{ donation.donor.user.email }}">
        </div>
      </div>
    </div>
  </div>

  <!-- Donation Details -->
  <div class="shadow mt-3 p-2 mb-5">
    <h4 class="text-center">Donation Details</h4>
    <div class="row p-2 justify-content-center">

      <div class="col-md-6">
        <div class="mb-3">
          {% if donation.donationpic %}
              <img class="rounded" src="{{ donation.donationpic.url }}" alt="Default Image" width="100%" >
          {% endif %}
        </div>
      </div> 

      <div class="col-md-6">
        <div class="form-group mt-1">
          <lable>Name</lable>
          <input class="form-control" readonly value="{{ donation.donationname }}">
        </div>

        <div class="form-group mt-1">
          <lable>Collection Location</lable>
          <input class="form-control" readonly value="{{ donation.collectionloc }}">
        </div>

        <div class="form-group mt-1">
          <lable>Donation Date</lable>
          <input class="form-control" readonly value="{{ donation.donationdate }}">
        </div>

        <div class="form-group mt-2">
          <lable>Status</lable>
          <input class="text-center 
          {% if donation.status == 'reject' %}bg-danger
          {% elif donation.status == 'pending' %}bg-warning text-dark
          {% elif donation.status == 'Donation Delivered Successfully' %}bg-success
          {% else %}bg-info text-dark
          {% endif %} 
          font-weight-bold text-light rounded-pill p-0 img-wa" 
          readonly value="{{ donation.status }}">       
         </div>

         <div class="form-group mt-1">
          <lable>Updation Date</lable>
          <input class="form-control" readonly value="{{ donation.updationdate }}">
        </div>

      </div>
    </div>

        <div class="form-group mt-1">
          <lable>Admin Remark</lable>
          <input class="form-control" readonly value="{{ donation.adminremark }}" style="height:100px">
        </div>

        <div class="form-group mt-1">
          <lable>Donation Area</lable>
          <input class="form-control" readonly value="{{ donation.donationarea.areaname }}">
        </div>

        <div class="form-group mt-1">
          <lable>Volunteer</lable>
          <input class="form-control" readonly value="{{ donation.volunteer.user.first_name }} {{ donation.volunteer.user.last_name }}">
        </div>

        <div class="form-group mt-1">
          <lable>Volunteer Remark</lable>
          <input class="form-control" readonly value="{{ donation.volunteermark|default_if_none:"" }}">
        </div>

        {% if donation.status == "Donation Received" %}
        <form method="post" enctype="multipart/form-data">
          {% csrf_token %}

          <div class="align-middle text-center">
            <lable >Donation Delivered Successfully</lable>
            <div colspan="3"> 
              <h5 class="text-secondary"><input type="radio" name="status" value="Donation Delivered Successfully" required> Donation Delivered Successfully</h5>
            </div>
          </div>

          <div class="align-middle text-center">
            <lable >Upload Donation Delivery PIC</lable>
            <div colspan="3"> 
              <input type="file" class="form-control" accept="image/*"  id="deliverypic" name="deliverypic" required>
            </div>
          </div>

          <div class="align-middle text-center mt-2">
            <td></td>
            <div colspan="3">
                <input type="submit" class="btn btn-primary px-5" value="Update" />
            </div>
          </div>


          {% endif %}
        </div>
          {% endblock main %}

  
   
  